[package]
name = "parse-changelog"
version = "0.4.8" #publish:version
edition = "2018"
rust-version = "1.51"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/taiki-e/parse-changelog"
keywords = ["changelog", "parser"]
categories = ["command-line-utilities", "parser-implementations", "text-processing"]
exclude = ["/.*", "/tools"]
description = """
Simple changelog parser, written in Rust.
"""

[package.metadata.docs.rs]
all-features = true
targets = ["x86_64-unknown-linux-gnu"]

[workspace]
resolver = "2"
members = ["bench", "tools/codegen"]

[[bin]]
name = "parse-changelog"
required-features = ["default"]

[features]
# When using this crate as a library, we recommend disabling the default features.
default = ["anyhow", "lexopt", "serde", "serde_json", "regex/unicode"]
# Implements serde::Serialize trait for parse-changelog types.
serde = ["serde-crate", "indexmap/serde-1"]

# Note: indexmap and serde are public dependencies.
[dependencies]
indexmap = { version = "1.5.2", features = ["std"] }
memchr = "2.4"
once_cell = "1"
regex = { version = "1.3", default-features = false, features = ["perf", "std"] }

anyhow = { version = "1.0.34", optional = true }
lexopt = { version = "0.2", optional = true }
serde-crate = { package = "serde", version = "1.0.103", optional = true, features = ["derive"] }
serde_json = { version = "1", optional = true }

[dev-dependencies]
easy-ext = "1"
